# | Auto Start |
# autostart your favorite applications here

exec-once = systemctl --user import-environment
exec-once = gnome-keyring-daemon --start --components=secrets,ssh,pkcs11 &
exec-once = noctalia &
exec-once = fcitx5 -d
exec-once = easyeffects --service-mode &