# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x0c141bff
bordercolor = 0x8293a2ff
dropcolor = 0x4ddad680
splitcolor = 0x97ccf9ff
focuscolor = 0x4ddad6ff
maximizescreencolor = 0x80d5d2ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0x97ccf9ff
globalcolor = 0x00504eff
overlaycolor = 0x00504eff
jump_label_decorate_fg_color = 0xdbe3edff
jump_label_decorate_bg_color = 0x232b32ff
jump_label_decorate_focus_fg_color = 0x003736ff
jump_label_decorate_focus_bg_color = 0x4ddad6ff
jump_label_decorate_border_color = 0x8293a2ff
group_bar_decorate_fg_color = 0xdbe3edff
group_bar_decorate_bg_color = 0x232b32ff
group_bar_decorate_focus_fg_color = 0x003736ff
group_bar_decorate_focus_bg_color = 0x4ddad6ff
group_bar_decorate_border_color = 0x8293a2ff
